### ISSUE TITLE
Sample doesn't work - unauthorized_client

### ISSUE THREAD

**Issue by segore** [skoruba/react-oidc-client-js#12]
Hi,

this sample doesn't seem to work anymore. When I start the client and click on "Login" the app forwards me to https://demo.identityserver.io/. This site displays the errormessage "Sorry, there was an error : unauthorized_client Unknown client or client not enabled".

After changeing Constants.clientId from 'spa' to 'interactive.public' it seems to work. 

Is that the correct/appropriate way to handle that problem? 

Thanks in advance for your answer.

**Comment by skoruba** [comment]
Fixed, thanks. 👍
