### ISSUE TITLE
An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: read ECONNRESET"

### ISSUE THREAD

**Issue by imad-mn** [skoruba/react-oidc-client-js#2]
Hello Jan, 
I got the error mentioned in the title when running yarn.

info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
**error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: read ECONNRESET".**
info If you think this is a bug, please open a bug report with the information provided in "C:\\gitprojects\\react-oidc-client-js\\src\\yarn-error.log".

I ran yarn into other projects without issues. Also, I could download that compression.1.7.2.tgz without issues if I put that url in the browser.

Please, let me know if you know how to fix this issue.
I'm running the latest version of each: node v10.16.0 and yarn v1.16.0

[yarn-error.log](https://github.com/skoruba/react-oidc-client-js/files/3237985/yarn-error.log)

**Comment by skoruba** [comment]
Sorry for delay, I will check it. :)

**Comment by skoruba** [comment]
I have updated whole project - all dependencies, please if you can - try to update to the latest master version. ;)
Thanks!

**Comment by skoruba** [comment]
I am closing this, feel free to reopen.
Thank you
