### ISSUE TITLE
Stops on sign-in callback

### ISSUE THREAD

**Issue by eloekset** [skoruba/react-oidc-client-js#3]
I followed the guide at readme.md and got this:
![image](https://user-images.githubusercontent.com/791721/60369357-9eb0cb80-99f3-11e9-868f-42205c368cb3.png)

...and there it stops.

**Comment by skoruba** [comment]
Please check console in browser, any js errors? Thanks

**Comment by eloekset** [comment]
![image](https://user-images.githubusercontent.com/791721/60383025-f9860980-9a6b-11e9-91cd-4e1b07962f12.png)

signin-callback.html:24 Error: Invalid response Content-Type: application/jwk-set+json; charset=UTF-8, from URL: https://demo.identityserver.io/.well-known/openid-configuration/jwks
    at XMLHttpRequest.req.onload (JsonService.js:40)

**Comment by skoruba** [comment]
Please try update package: oidc-client to latest version - 1.8.2. Let me know please, if it will help. :)

**Comment by eloekset** [comment]
Doesn't seem to make any difference.
1. `yarn upgrade oidc-client@1.8.2`
2. Change **AuthService.ts**  `getUser()` function to have return type `Promise<User | null>` because of TypeScript changes
3. `yarn start`
4. Click the login button
5. Return from IdSrv makes the same error occur:
![image](https://user-images.githubusercontent.com/791721/60383687-7cab5d80-9a74-11e9-8751-feacb2f581c8.png)

**Comment by skoruba** [comment]
Ok, let me check it. Thx

**Comment by skoruba** [comment]
I have updated whole project - all dependencies and switch to create-react-app, because original repository with typescript support is deprecated.
- Please, try to clone latest code from master. :)
Thanks!

**Comment by eloekset** [comment]
Thanks @skoruba! 
I can confirm that it works 💯
