### ISSUE TITLE
Error 500 on authentication

### ISSUE THREAD

**Issue by kamalraturi** [skoruba/react-oidc-client-js#4]
The client works well with demo STS sevrer, but when I changed it to Skoruba STS and I tried to login SPA client (ca-react-app) it gives error as:This page isn’t working. Error: iserver.***.com is currently unable to handle this request.HTTP ERROR 500.

**Comment by skoruba** [comment]
Can you send detailed error message or check error log on IS?
Thanks.

**Comment by kamalraturi** [comment]
Here is the log, Kindly see your email also:

{
  "TimeStamp": "2019-11-25T08:32:13.7621614",
  "Level": "Fatal",
  "Message": "Unhandled exception: \"Error mapping types.\r\n\r\nMapping types:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nType Map configuration:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nDestination Member:\r\nAllowedGrantTypes\r\n\"",
  "MessageTemplate": "Unhandled exception: {exception}",
  "Exception": "AutoMapper.AutoMapperMappingException: Error mapping types.\r\n\r\nMapping types:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nType Map configuration:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nDestination Member:\r\nAllowedGrantTypes\r\n\r\n ---> System.InvalidOperationException: Grant types cannot contain spaces\r\n   at IdentityServer4.Models.Client.ValidateGrantTypes(IEnumerable`1 grantTypes)\r\n   at IdentityServer4.Models.Client.set_AllowedGrantTypes(ICollection`1 value)\r\n   at lambda_method(Closure , Client , Client , ResolutionContext )\r\n   --- End of inner exception stack trace ---\r\n   at lambda_method(Closure , Client , Client , ResolutionContext )\r\n   at lambda_method(Closure , Object , Object , ResolutionContext )\r\n   at IdentityServer4.EntityFramework.Mappers.ClientMappers.ToModel(Client entity)\r\n   at IdentityServer4.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId)\r\n   at IdentityServer4.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId)\r\n   at IdentityServer4.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId)\r\n   at IdentityServer4.Validation.AuthorizeRequestValidator.LoadClientAsync(ValidatedAuthorizeRequest request)\r\n   at IdentityServer4.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject)\r\n   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)\r\n   at IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)\r\n   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)\r\n   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)\r\n   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)",
  "Properties": {
    "exception": "Error mapping types.\r\n\r\nMapping types:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nType Map configuration:\r\nClient -> Client\r\nIdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client\r\n\r\nDestination Member:\r\nAllowedGrantTypes\r\n",
    "SourceContext": "IdentityServer4.Hosting.IdentityServerMiddleware"
  }
}

**Comment by kamalraturi** [comment]
Here it is:
{
  "TimeStamp": "2019-11-25T08:39:05.3944236",
  "Level": "Error",
  "Message": "Request validation failed",
  "MessageTemplate": "Request validation failed",
  "Properties": {
    "SourceContext": "IdentityServer4.Endpoints.AuthorizeEndpoint"
  }
}

**Comment by kamalraturi** [comment]
> Here it is:
> {
> "TimeStamp": "2019-11-25T08:39:05.3944236",
> "Level": "Error",
> "Message": "Request validation failed",
> "MessageTemplate": "Request validation failed",
> "Properties": {
> "SourceContext": "IdentityServer4.Endpoints.AuthorizeEndpoint"
> }
> }

{
  "TimeStamp": "2019-11-25T08:54:43.0112916",
  "Level": "Error",
  "Message": "Invalid redirect_uri: \"https://ispaclient.racybit.com/signin-callback.html\"\nAuthorizeRequestValidationLog { ClientId: \"ca-react-app\", ClientName: \"ca-react-app\", RedirectUri: null, AllowedRedirectUris: [\"https://ispaclient.racybit.com\"], SubjectId: \"9ffd5469-2665-431f-94f9-acb0dea0665d\", ResponseType: null, ResponseMode: null, GrantType: null, RequestedScopes: \"\", State: null, UiLocales: null, Nonce: null, AuthenticationContextReferenceClasses: null, DisplayMode: null, PromptMode: null, MaxAge: null, LoginHint: null, SessionId: null, Raw: [(\"client_id\": \"ca-react-app\"), (\"redirect_uri\": \"https://ispaclient.racybit.com/signin-callback.html\"), (\"response_type\": \"code\"), (\"scope\": \"openid profile email api smartproj-api\"), (\"state\": \"b9194ff6878d4d12af4120d74b83f897\"), (\"code_challenge\": \"1TMimwhypgFi5XQea15dVwMs9BKCCJeyV6S7EDhNpPQ\"), (\"code_challenge_method\": \"S256\")] }",
  "MessageTemplate": "Invalid redirect_uri: {detail}\n{@requestDetails}",
  "Properties": {
    "detail": "https://ispaclient.racybit.com/signin-callback.html",
    "requestDetails": {
      "ClientId": "ca-react-app",
      "ClientName": "ca-react-app",
      "RedirectUri": null,
      "AllowedRedirectUris": [
        "https://ispaclient.racybit.com"
      ],
      "SubjectId": "9ffd5469-2665-431f-94f9-acb0dea0665d",
      "ResponseType": null,
      "ResponseMode": null,
      "GrantType": null,
      "RequestedScopes": "",
      "State": null,
      "UiLocales": null,
      "Nonce": null,
      "AuthenticationContextReferenceClasses": null,
      "DisplayMode": null,
      "PromptMode": null,
      "MaxAge": null,
      "LoginHint": null,
      "SessionId": null,
      "Raw": {
        "client_id": "ca-react-app",
        "redirect_uri": "https://ispaclient.racybit.com/signin-callback.html",
        "response_type": "code",
        "scope": "openid profile email api smartproj-api",
        "state": "b9194ff6878d4d12af4120d74b83f897",
        "code_challenge": "1TMimwhypgFi5XQea15dVwMs9BKCCJeyV6S7EDhNpPQ",
        "code_challenge_method": "S256"
      }
    },
    "SourceContext": "IdentityServer4.Validation.AuthorizeRequestValidator"
  }
}

**Comment by skoruba** [comment]
Check this one:
>Invalid redirect_uri: "https://ispaclient.racybit.com/signin-callback.html

You have probable redirect uri: https://ispaclient.racybit.com

**Comment by kamalraturi** [comment]
> Check this one:
> 
> > Invalid redirect_uri: "https://ispaclient.racybit.com/signin-callback.html
> 
> You have probable redirect uri: https://ispaclient.racybit.com

I also set this but still same issue. Kindly check your email for login details, if possible. Thanks!

here is also the Api startup:

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                // base-address of your identityserver
                options.Authority = "https://iserver.****.com";

                // name of the API resource
                options.ApiName = "smartproj-api";
                });
            services.AddControllers();
        }
